# Generated by Django 4.0 on 2022-01-04 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_operation_share_alter_portfolio_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
