# Generated by Django 4.0 on 2022-01-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_quantitiy_operation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='share',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stock.stock'),
        ),
    ]
