# Generated by Django 4.0 on 2022-01-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_operation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='temprary_amount',
            new_name='avg_price',
        ),
    ]
