# Generated by Django 4.0 on 2022-01-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_rename_temprary_amount_portfolio_avg_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
