version: '3.8'
services:
  web:
    build: .
    restart: always
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./finance:/usr/src/app/finance
      - ./stock:/usr/src/app/stock
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

volumes:
  redisdata: